---
title: "Untitled"
output: html_document
date: "2023-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

我国近期颁布了《关于进一步完善医疗卫生服务体系的意见》，明确指出“到2025年，医疗卫生服务体系进一步健全，资源配置和服务均衡性逐步提高，重大疾病防控、救治和应急处置能力明显增强，中西医发展更加协调，有序就医和诊疗体系建设取得积极成效。到2035年，形成与基本实现社会主义现代化相适应，体系完整、分工明确、功能互补、连续协同、运行高效、富有韧性的整合型医疗卫生服务体系，医疗卫生服务公平性、可及性和优质服务供给能力明显增强，促进人民群众健康水平显著提升”。

医养结合促进整合医疗卫生服务体系实施路径探讨


实现“健康中国”战略建设，需要构建全人群、全方位、全生命周期的整合医疗卫生服务模式，该模式能改善卫生服务碎片化的情况，缓解老龄化及疾病谱慢性病化所带来的医疗费用持续攀升的压力。各项医疗服务的无缝衔接对设计出符合本国特点的医疗卫生服务整合体系显得尤为重要。
本文综述了英国、法国、日本等国家整合医疗卫生实践，分析整合医疗卫生服务的内涵与特征，综述国际经验、梳理关键环节，由此总结对我国推进整合医疗卫生服务的借鉴经验。 

一、	整合卫生的内涵与特征 

兰德公司研究人员将整合卫生定义为跨专业、跨机构、跨支持体系的协同的患者服务，服务在时间和就诊上是连续的，以患者的需求和喜好为导向，患者及其照顾者对于维持最佳健康状态有共同责任[1]。有的学者界定为：在组织结构上建立医疗资源的纵向整合和分工协作机制， 在功能上强调以健康需求为导向，整合医疗、预防、保健、康复、健康教育和健康促进等服务，以提供系统、连续、全方位的服务[2]。世界卫 生组织（World Health Organization，WHO）提出了“整合医疗卫生服务”工作定义，即对卫生服务进行组织和管理，确保居民在需要的时候获得所需的卫生服务，服务提供方式为患者/居民喜闻乐见并易于接受，提 供的服务达到预期效果并物有所值[3]。 虽然不同国家的实践和学者对于整合医疗卫生概念的表述有所不 同，但其理念、结构和最终达到的效果有共同点。

其一，在理念上以人为本，以人为出发点，并基于健康状况提供个 性化的医疗服务。 其二，在结构上呈现多维、扁平化，多种机构形成有效的伙伴关系，整合内容一般包括组织整合、功能整合、人员整合、规范整合、临床整合和系统整合[4]。其结构从宏观到微观分为3个层次：第一个层次为卫生服务筹资体系和部门间的协作与整合，使资金拨付、服务管制或服务提供在各部门之 间的合作制度化[5]。第二个层次是资源整合，横向整合是围绕临床上的卫生保健服务进行的资源整合，纵向整合是不同水平和级别的卫生保健服务之间的整合[6]。第三个层次是服务整合，是需求驱动下服务意识提高和服务模式变革下的新实践方式，分为临床服务整合与支持性功能整合2个部分，前者包括初级卫生保健、全科服务、专科服务、康复服务和护理服务的整合，后者主要是人力资源、支付管理、财务管理、绩效管理、信息系统等关键激励约束机制和支持系统的整合[7]。

其三，强调服务的连续性，注重患者感受度。它不仅考虑到个体单次服务提供合适有效，更考虑到其接受的各种服务之间、不同时间序列服务之间以及不同生命周期服务之间的连贯和衔接。从患者角度来看就是一站式服务，关键的问题是应该将什么服务纳入并组合在一起，管理支持系统应该如何组织以更好地提供这些服务。患者在服务过程中要积极参与和互动，因为整合是基于患者的需求和偏好。对服务提供者来说，整合可以在单个医疗服务机构内部、同一层次的医疗服务机构之间、不 同层次医疗服务机构之间进行。人员、临床和相关规范的整合非常重要，否则服务提供机构虽已高度整合在一起，但患者却经历着非常低程度的整合服务[8]。 

二、国际上整合医疗卫生体系的关键环节及主要举措 根据英国、法国、日本等国家的整合医疗卫生实践经验，这些国家在治理架构、流程整合、能力建设、激励机制和信息方面取得了有益经验。其中，建立治理架构是前提，而服务内容与流程整合、服务人员技能与角色转化、筹资与绩效激励机制和信息化支撑等是实现整合卫生的关键举措。 
（一）治理架构整合：目标、预算，部门、机构 整合医疗卫生体系的治理与管理架构分为政府部门层面的整合与医Groups，CCGs）由当地的全科医师主导，全科医师、护士及其他相关 专业人士共同负责当地卫生服务规划、资源配置、服务委托购买、服务提供。 不同政府部门间达成共识后，机构整合的关键是确定机构定位、分工与协作机制。英国地方政府自主性较大，多个地方CCGs 形成统一的 委托整合型服务的标准，基于优先目标确定服务委托意向。整合医疗卫生体系中，需要合并部分机构以减少角色和职能的重复[12]。医院改革的方向是减少医院和床位数量，将服务集中在更少的地点，并重新配置专科服务，如整形、孕产妇和儿科服务会更加集中[13]。同时，增加居家服务，开展联合全科服务、社会服务、精神卫生、公共卫生、社区护理以及部分医院专科服务的整合型服务社区建设[14]，以满足医院服务减少的需求空缺。日本则通过法律和/或规定的形式确立了机构的功能定位和转诊要求[15]。在医疗机构间的协作方面，既有医院与诊所间的双向转诊，区域医疗医院一般有“病诊转诊室”或“区域医疗转诊室”，设有传真、电话和网络平台供患者进行预约、转诊；也有诊所与诊所间的转诊，不同诊所的专科特色不相同，诊所间会在区域内根据患者需求进行转诊[16]。 在床位管理上，区分一般病床和疗养型病床，以此对急性期住院患者和慢性期住院患者进行区分，并针对不同的病床属性制定相应的医护人员 配置标准及医疗设备配置标准[17]。 
（二）整合内容与流程：风险分层、按需分流 整合型服务体系大多采取健康风险管理机制，对不同健康风险人群实施差异化管理和服务。如英国伦敦市的卡姆登区建立了风险分层工具来识别风险人群和重点人群，根据需求评估结果对不同人群分别建立整合型的服务路径，制定具体的诊断、服务及转诊标准。加强风险人群和重点人群的疾病预防和健康管理，避免不必要的住院[18]。卡姆登区基于医疗服务利用数据，将人群从低风险到高风险分为6 级：①未发生二级 4 5

他山之石
医疗服务；②健康个人、对医疗服务仅有限需求；③孕产妇、无慢性病的急性患者，对二级医疗服务仅潜在有限需求；④有慢病的健康个人； ⑤慢病患者，需要规律管理、监测；⑥慢病患者，对二级医疗服务有潜 在高需求。第6级风险人员涵盖急诊就医、床日数3d 以上，有1 项慢病； 或急诊就医、床日数3d 以上，有2项或以上慢病；或计划就医、床日 数3d 以上，有慢病人员。该地区74% 的人群较为健康，患有慢性病且 需常规监测、管理的人群约占3% ；而老年人健康人群占38%，21% 需要常规检测和管理。这样可以精准地提供医疗卫生服务。该区不同健康 风险人群分流路径见图1。 图1 英国卡姆登区整合健康服务路径 4 5他山之石
英国、法国均针对重点疾病设置了专病防治体系，在服务流程、临 床路径和规范上进行了整合。随着老龄化的加剧，老年人心脑血管病患 发病率持续上升，脑卒中的发生率提高，医疗成本和社会成本高。脑卒 中防治被多个国家列为优先病种。研究发现，患者及家庭、朋友不了解 发病征兆，处理不够及时，或者发现时没有送到适当的诊疗机构，医疗 机构间（尤其是医院与康复机构之间）配合不够通畅是影响治疗效果的 主要原因。针对这些问题，首先把宣传教育工作前置，宣传疾病的危害 程度以及导致疾病的原因，以及一旦发现脑卒中的症状应该怎么处理。 其次，建立“家—诊疗机构—医院—康复机构—居家护理”的分级诊疗 流程和转诊标准，并且以法规的形式强制执行。 （三）整合人员技能与角色转换 从患者角度来看，整合医疗卫生是一站式服务，通过一个接入点获 取所需要的服务。而人员的跨边界整合，不同服务、不同机构、不同体 系人员之间的界限被认为是提供整合型服务的关键障碍。这样的体系需 要整合多学科人员共同提供服务，对卫生技术人员技能有新的要求[19]。 全科医师通常作为这类新服务模式的核心，与其他基层卫生人员和社区 工作人员联系密切[20] ；要求医师助理增加管理需求的能力、拓展服务 团队的技能[21，22]。英国出现了支持整合型服务的新角色—服务导航者， 其主要职责是支持患者个人健康计划，促进患者参与，确保其获得所需 服务。法国脑卒中医院治疗过程根据患者情况，协调了急诊、放射、造影、 心血管、脑神经、护理师、康复陪伴师等专业人员共同开展诊疗。日本 在1997 年引入出院计划的概念，以缩短不必要的住院时间，根据患者 和其家属的情况，选择最合适的出院场所，进行必要的安排、教育指导 和提供系统化的服务；同时设置了出院计划指导者这一角色来推动出院 6 7他山之石
计划的实施，一般由负责出院的护士根据患者风险分类标准选择适合出 院计划的患者，转诊至其他医疗机构，或接受居家、护理机构和社区机 构等服务，跟踪患者状况、了解其需求，协调专业人员的诊疗建议[23]。 （四）整合筹资与绩效激励机制 筹资与绩效激励机制是整合医疗卫生持续发展的动力，通过协同医 疗机构绩效考核和医疗保险支付政策对服务提供模式进行引导，促进资 源的合理配置和流动。对于整合体系的评估，包括从组织合作进行结构 评价、服务提供进行过程评价、纵向整合结果（质量、效益、效率、效果、 公平、可及等）进行评价[24]。英国的NHS 临床执业联盟和全科医师体系， 其评估体系分为4 个方面：财务表现、生产率、等候时间和临床质量[25]， 这与其医疗资源紧张、医疗等候时间过长有关。 在激励机制上，英国全科医师仍以按人头支付为主（约占75%）， 针对重点关注和需要增强的服务项目，构建了基于质量与结果框架 （quality and outcomes framework，QOF）的奖励支付制度。参与这项考 核体系的全科医师可提前获得部分QOF 拨款，服务完成后，根据考核 结果将其余的部分奖励给全科医生[26]。2014 年的QOF 包括19 个临床 项目（高血压、糖尿病安宁疗护等）和6 个公共卫生项目（心脑血管疾 病的一级预防等）。 同时，支付方式改革支持新的医疗护理综合模式， 如集多学科专科服务、初级保健、急症救治为一体的服务，按人头支付 包括初级保健、二级医疗、社区服务、精神卫生和社会照护在内的服务。 日本的医疗保险报销政策以点数的形式向一级医疗圈倾斜。对于患 者的激励，通过医疗保险差额支付政策，除急诊外，患者均需凭借一级 医疗圈中诊所医师的介绍信才能到上一级医疗圈进行治疗。若患者直接 前往上级医疗圈就诊，不仅将自行承担全部的医疗费用，还需缴纳额外 6 7他山之石
的医疗服务费，且多数上级医院不接受此类门诊患者[27]。对于机构的 考核，通过收费标准激励医疗机构自发进行转诊。医院若能够达到区域 医疗支援医院的14 项规定标准，则每年可以获得额外的财政专项补助， 提高医疗服务价格点数。这14 项规定即是法律对区域医疗支援医院职 能的定位，其中便包括双向转诊率，要求初诊患者中凭借介绍信转诊而 来的患者比例达到80% 以上，或向上转诊比例达到60% 且向下转诊比 例达到30%，或向上转诊比例达到40% 且向下转诊比例达到60% 等。 通过医疗保险点数激励的形式，使转诊对各级医疗机构均为有利，以此 提高医疗机构在双向转诊机制方面的主动性[28，29]。 （五）信息化的支撑作用 互联互通的健康、诊疗信息是整合医疗卫生服务的技术保障。信息 化首先可用于患者自身健康管理。对于管理者来说，基于信息化可实时、 准确地确定居民健康服务需要，这是实现分类管理、整合服务的基础。 根据需要提供服务的体系，有效支持了健康服务资源在不同老年群体中 的合理分配，促进卫生体系总体绩效的提高，并可实现对各医疗团队和 医疗机构质量及绩效的定期监测。对于服务提供者来说，机构间可实现 跨组织、可共享的电子病历系统，减少重复检查，促进治疗方法协同。 三、我国整合医疗卫生实践面临的问题和瓶颈 我国在医疗资源整合方面已开展了多种形式的探索，主要表现为建 立各级医疗机构的医疗协作体，或专科医院联盟。整合的层次主要在组 织管理体系和机构整合，服务整合多为支持性功能整合，比较松散的联 合体主要是技术输出和上下转诊，在人事、财务、检验、采购、信息等 方面较为紧密地开展了一体化建设。但是离以人为本、以健康为导向的 整合医疗卫生服务体系还有一定差距。国际经验对我国进一步推进整合 服务具有一定借鉴意义。 8 9他山之石
（一）多部门协同、需方引导机制不完善 目前卫生管理的职能分散在财政、卫生等多个政府部门，部门间难 以达成共同的目标、建立通畅的协作机制。已有的整合探索偏重于供方 角度，而“以人为本”的整合服务体系应从需方出发。无序就诊情况固 然与自由就诊制度有关，但诊疗过程中，患者需求没有得到科学的评估、 就诊没有专业人士有效引导也是造成无序就医的原因之一。 （二）资源配置不平衡、利用不充分问题并存 资源配置的不平衡主要表现在医疗资源集中在医院，预防、护理、 康复等急性期后诊疗资源短缺。2016 年，全国各类医疗卫生机构床位数 为741.05 万张、卫生技术人员共计845.44 万人，医院的构成比分别为 76.77%、64.05%，资源配置结构呈现“倒三角”结构，社区卫生服务机 构人员少、工作任务重，健康管理难以开展持续追踪。全国康复医院和 护理院仅有495 家、240 家，平均开放床位分别为5.17 万张、3.19 万张， 分别占全国医疗卫生机构总开放床位的0.73%、0.45%，康复、护理资 源和服务量构成比均较低[30]。 社区、康复、护理等资源短缺，而社区却出现资源空置等现象。 2016 年全国医院的病床工作日为311d，病床平均周转次数为32.00，病 床使用率为85.30%。社区卫生服务中心（站）的病床工作日为197d， 病床平均周转次数为17.90，病床使用率为54.10%[30]，这与机构间的协 作渠道不通畅有关。虽然信息化建设在如火如荼地开展，但各机构间数 据尚未实现互联互通，家庭医生不掌握患者在上级医院的就诊情况，而 上级医院也无法了解转院或出院后的情况。例如，针对脑卒中建立了专 病网络，但在疾病急性期过后的康复阶段，三级医院不了解协作网络床 位空置情况，患者转诊依靠医生的私人关系为主。 8 9他山之石
（三）缺乏临床服务规范，标准执行力度不够 目前整合体系探索主要在机构协作、支持性功能整合层面，对需整 合服务的疾病种类以及不同疾病患者的临床路径、整合服务内容还少有 涉及。我国临床诊疗规范多由各学会制定，没有定期更新，及时性、约 束性不强。医疗机构之间临床诊疗规范不统一，不利于建立标化临床服 务路径和转诊会诊标准，从而降低服务的整体性以及患者的就医感受。 此外，我国临床诊疗规范为参考性文件，不是法律性强制执行，存在供 方不按标准执行和需方不依从的问题。医务人员在实际操作过程中没有 按照规范执行的情况较为时有发生，如没及时转诊康复阶段患者[31]、怕 担责任而不当转诊等[32]。而部分患者对向下转诊表现排斥、依从性低， 也是导致患者转诊难的原因之一[33]。 （四）人员多学科服务、协作能力培养不足 首先，医务人员能力培养缺乏对多学科知识、整合协作思维的培训。 医师规范化培训按照不同学科专业进行设置，交叉学科训练缺乏，造成 了学科专业壁垒。由于知识储备的局限性，当诊疗跨学科的复杂病例时 将影响诊治效果。对于患者而言也带来了许多不便，出现一次就诊挂多 个科的现象。 其次，不同级别医务人员间的整合不足。从供方来看，基层医疗卫生机 构中，家庭医生未能掌握签约居民各级医疗机构就诊信息，成为各级各类 医疗机构之间上下联动的“纽带”。 二级及以上医疗机构中，信息平台并未 构建统一的、标准化的临床诊疗规范辅助系统，也没有形成标准化的患者诊 疗流程。从需方来看，自由就诊制度下患者对临床规范的依从性欠佳；而缺 乏医务人员对健康连续、全程的管理，导致患者盲目就医。 （五）考核仍以机构为单位，缺乏一体化考核 对卫生体系的投入（包括财政投入与医疗保险支付）仍是以单体 10 11他山之石
机构为单位。尽管医疗联合体（以下简称“医联体”） 的实践在广泛开 展，但医联体内的各家公立医疗机构大部分为独立法人，缺乏对整个 医联体的激励与绩效考核机制，机构间共享、协作、上下转诊联动等 能够体现服务整合性的功能，缺乏资金的“指挥棒”加以引导。对医 务人员而言，也没有形成以健康结果为导向的正向激励机制。医疗机 构绩效考核主要基于个人特征、工作量甚至医疗收入核定，重“诊疗” 而非“提升健康”。 （六）数据碎片化，数据分享和挖掘不够 医疗数据虽已联网，但由于缺乏全程管理，患者就医分布呈现散点 状，医院的专科医师无法对其整体健康状况作出正确判断和评价。同时， 患者自身也不能随时掌握其自身的健康数据，只能分别从就医的各家机 构获得。信息局限在管理平台集成，医疗机构间的数据还不能对接，患 者的诊疗信息仍为孤岛，没有达到以信息化促进诊疗效率提高、促进健 康管理模式转变的效果。具体表现在数据标准化程度还有待提高、数据 开发和管理利用不足。例如，未对居民进行健康风险分层，患者需求没 有得到有效引导；没有运用即时系统对医疗卫生资源（如床位）进行配置， 造成床位空置与“一床难求”现象并存等。 四、推进整合医疗卫生体系的建议路径 根据英国、法国、日本等国家的整合医疗卫生实践经验，整合医疗 卫生服务体系有6 大关键环节：基于健康档案与医疗记录建立风险分层 模型；建立整合部门和机构协作网络；构建患者分流体系与临床诊疗、 转诊标准；组建整合团队和联络员，加强专业间协作；设计和实施以结 果为导向的考核、激励机制；借助信息化建立医疗服务共享和绩效管理 平台（见图2）。 结合我国整合医疗卫生体系的探索及存在问题，提出 推进整合体系建设的主要举措。
（一）统筹与协作：部门机构协同，资源有效配置 政府部门间要明确共同的服务目标、职能分工和预算分配规则。 2018 年我国部委改革，部门间的分工有了新的变化，主导健康服务的 是卫生健康委员会和医疗保健局，前者是健康服务提供方，后者相当于 医疗服务的购买方，拥有定价、采购和支付的功能。两个部门更需要在 服务目标、机构定位、资源配置与支付方面建立协调的规则。在整合体 系中，要改变医疗卫生机构的功能定位、资源配置，例如尽量控制医院 急性住院床位，增加康复期、家庭虚拟病房资源。资源配置结构要与功 能定位匹配，增设康复、护理院资源，并且通过财政投入、价格调整等 政策支持为这些机构创造良好的经济运行机制。同时，加强对医疗资源 的统筹管理。例如，在脑卒中服务网络机构中，通过信息化技术连通各 图2 整合医疗卫生体系的6个关键环节 12 13他山之石
机构的床位利用状态，实现资源的统筹、有效利用。 （二）分层与整合：需求合理分层，服务内容整合 从需方出发，通过健康档案和诊疗大数据，全面掌握居民的身体 健康状态及所患疾病的严重程度，建立健康风险分层模型以开展针对性 的、差别化的服务，重点锁定风险较大人群。可首先选择重点、共性健 康问题（如常见的重点病种），从临床层面进行整合，包括患者分流路径、 服务内容、服务流程、临床规范、转诊标准、转诊流程等，为患者提供 一体化服务。加大临床标准的执行力度，借助信息化，通过嵌入临床标准， 对供、需双方的行为进行监管。 （三）能力的培养：多学科能力培养，设置联络员 整合医疗卫生服务团队成员在专业上既有分工更有协作，在人才培 养培育阶段加强交叉学科知识、多学科团队协作能力的培养。在服务过 程中，建议设置纽带型角色，例如联络员，负责健康需求的评估、就诊 引导以及上下转诊的协调工作。根据需求，设置包含相关医学专业、全科、 护理、心理、社会支持等各个专业背景服务团队，以提供一体化服务。 （四）考核与激励：整体评价体系，有效经济激励 激励机制是激发内在动力的最关键举措。整合医疗卫生服务体系的 考核体系要区别于单体机构的考核。鉴于我国整合医疗卫生服务体系处 于起步阶段，需要从多个环节进行考核。以“结构—过程—结果”为评 价模型：结构要素如组织框架、功能性组织、人力和财务管理；过程要 素如医疗过程连续性、服务和人员整合程度、信息互联互通和利用程度 等；结果要素如治疗结果、人群健康结果[35]。建立与考核结果挂钩的财 政投入、医疗保险资金支付机制，以及医务人员薪酬分配制度。 12 13他山之石
参考文献 [1] SINGER S J，BURGERS J，FRIEDBERG M，et al. Defining and measuring integrated patient  care：promoting the next frontier in health care delivery[J]. Med Care Res Rev，2011，68（1）： 112-127.  [2] MUR-VEEMAN I，HARDY B，STEENBERGEN M，et al. Development of integrated care in  England and the Netherlands：managing across public-private boundaries[J]. Health Policy，2003， 65（3）：227-241.  [3] WORLD HEALTH ORGANIZATION. Framework on integrated，people-centred health services[R].  Geneva：World Health Organization，2016.  [4] FULOP N，MOWLEM M C，EDWARDS N E. Building integrated care：lessons from the UK and  elsewhere[R]. London：the NHS Confederation，2005.  [5] 代涛，陈瑶，韦潇. 医疗卫生服务体系整合：国际视角与中国实践[J]. 中国卫生政策研究， 2012，5（9）：1-9.  [6] Peter R. Kongstvedt. Essentials of Managed Health Care （Fifth Edition）[M]. Reston，VA ：Jones  and Bartlett Publishers，2007.  [7] 匡莉，甘远洪，吴颖芳. “纵向整合”的医疗服务提供体系及其整合机制研究[J]. 中国卫生事业 管理，2012，29（8）：564-566.  [8] 匡莉，马远珠，甘远洪. 整合的卫生服务：来自WHO的定义与阐释[J]. 医学与哲学，2011，32 （13）：1-3.  [9] 于广军. 英国国家卫生服务体系新一轮改革及其对我国的启示[J]. 中国卫生资源，2015，18 （5）：371-373.  [10] 谢春艳，金春林，王贤吉. 英国国民健康服务体系新一轮改革解析[J]. 中国医院管理，2015，35 （2）：78-80.  [11] 谢春艳，金春林，王贤吉. 英国整合型保健发展经验及启示[J]. 中国卫生资源. 2015，18（1）： 71-74.  [12] BIRMINGHAM CITY COUNCIL. Our plan to improve the health and wellbeing of people living in  Birmingham and Solihull[EB/OL]. [2018-02-24]. https://www. birmingham. gov. uk/stp.  [13] Cambridgeshire And Peterboroug CCG. Cambridgeshire and Peterborough Health and Care System  Sustainability and Transformation Plan[R]. Cambridgeshire：Cambridgeshire And Peterboroug CCG.  2016.  [14] NATIONAL HEALTH SYSTEM CUMBRIA CCG. STPs[EB/OL]. [2018-2-22]. http://www.  northcumbriaccg. nhs. uk/about-us/STP/STPs. aspx.  [15] 张莹，邵静，丁海云. 日本整合型医疗卫生服务体系构建的经验与启示[J]. 中国卫生政策研究论 坛. 2012.  [16] 顾亚明. 日本分级诊疗制度及其对我国的启示[J]. 卫生经济研究，2015（3）：8-12.  [17] 孟开. 从日本第四次医疗法的修改看医院病床分类[J]. 国外医学，2004，21（3）：120-126.  [18] Camden Sustainable Insights Partnership. Population Health Management[R]. London：2015.  14 15他山之石
[19] Paul Williams. The competent boundary spanner[J]. Public Administration，2002，1（80）：103– 124.  [20] Chris Ham，Hugh Alderwick，Phoebe Dunn，et al. Delivering sustainability and transformation  plans From ambitious proposals to credible plans[R]. London：The King’s Fund. 2017.  [21] BIENKOWSKA-GIBBS T，KING S，SAUNDERS C，et al. New organisational models of primary  care to meet the future needs of the NHS：a brief overview of recent reports[EB/OL]. [2018-02-22].  www. rand. org/pubs/research_reports/RR1181. html.  [22] DRENNAN V M，HALTER M，JOLY L，et al. Physician associates and GPs in primary care：a  comparison[J]. Brit J Gen Pract，2015，65（634）：e344–e350.  [23] 孙皎. 介绍日本出院计划发展的近况[J]. 吉林医学. 2006，27（4）：398-400.  [24] ANDERSON G，HORVATH J. The growing burden of chronic disease in America[J]. Public Health  Rep，2004，119（3）：263-270.  [25] MARTIN G，MAURO L，CAROL P，Can governments do it better？Mergermania and hospital  outcomes in the English NHS[J]. Health Care Finan，2004，31（1）：73-84.  [26] 谢春艳，何江江，胡善联. 英国初级卫生保健质量与结果框架解析[J]. 中国医院管理，2015，35 （7）：78-80.  [27] 张莹. 日本医疗机构双向转诊补偿制度的经验与启示[J]. 中国卫生经济，2013，32（4）：93-94.  [28] 日本厚生劳动省. 医療法[EB/OL]. [2018-02-22]. http://wwwhourei. mhlw. go. jp/cgi-bin/t_docframe.  cgi？MODE=hourei&DMODE=CONTENTS&SMODE=NORMAL&KEYWORD=&EFSNO=200.  [29] 孟开，张玲. 日本医疗法的五次修改与医院管理[J]. 中华医院管理杂志，2010，26（5）：397- 400.  [30] 国家卫生和计划生育委员会. 中国卫生和计划生育统计年鉴2017[M]. 北京：中国协和医科大学 出版社，2017.  [31] 吴秋兰，曾广民，王谏珠，等. 社区高血压的转诊现状及分析[J]. 中国医药指南，2012（33）： 686-687.  [32] 潘景业，徐长恩，全世超. 双向转诊下转难原因的“冰山角”分析[J]. 中国卫生事业管理， 2009，26（5）：300-301.  [33] 王珩，冯占春，李鹏. 双向转诊中向下转诊的影响因素分析[J]. 中华医院管理杂志，2012，28 （4）：268-270.  [34] 张亮，张研，唐文熙，等.健康整合：引领卫生系统变革[M].北京：科学出版社，2014：137- 146. （责任编辑：信虹云）
